name: Docker

on:
  push:
    branches:
      - "master"

jobs:
  push:
    name: Update dockerhub image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build front
      uses: docker/build-push-action@v3
      with:
        context: prep
        push: true
        tags:
          - marcpartensky/thaiwara:latest
          - marcpartensky/thaiwara:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
