name: Docker

on:
  push:
    branches:
      - "master"

jobs:
  # test:
  #   name: Update dockerhub image
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - 

  push:
    # needs:
    #   - test
    name: Update dockerhub image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: name/app
        tags: |
          type=raw,value={{date 'YYYY-MM-DD'}}
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get current date
      id: date
      run: |
        echo "{date}={$(date +'%Y-%m-%d')}" >> $GITHUB_STATE
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          marcpartensky/thaiwara:latest
          ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
